#!/usr/bin/env python3
"""
patch_all_chapters.py — Full content update for Two Layers.
Updates data/two-layers.json with full EN prose for all 10 chapters (both sides).
The artifact_svg function was patched directly in build.py via Edit tool.
Runs build.py at the end.
"""
import json
import subprocess
from pathlib import Path

ROOT = Path(__file__).parent

# ── CHAPTER CONTENT ──────────────────────────────────────────────────────────
# Ch 1 simulation is ALREADY WRITTEN — no key 1 here.

CH_2026 = {
    2: [
        "The morning starts the same. The app wakes me at 6:07 with a tone that is scientifically calibrated to produce minimum cortisol spike. I have been waking at 6:07 for eleven months.",
        "I do not look at my phone first. That is the rule. I lie on my back for two minutes and let the ceiling be just a ceiling. Then I get up and I do the fourteen vitamins. In order. With water at exactly the temperature the tap produces before the hot kicks in.",
        "Omega-3. Vitamin D. Magnesium glycinate. Then the B-complex and the NAC. I have a system. Systems are how you avoid decisions. Decisions are where the day leaks out.",
        "I make coffee. One cup. Forty grams of beans weighed on the small kitchen scale because I once read that consistency in extraction produces consistency in cognition and I cannot remember now whether I read that or whether I told it to an AI and it confirmed it, which is not the same thing.",
        "I open the laptop and the AI is already there. I describe what I need. A covered pedestrian bridge for the Nonthaburi waterfront. Forty meters. Needs to breathe but not let rain in. I say breathe and not let rain in in the same sentence and the AI does not find this contradictory. The AI never finds anything contradictory. This is the first thing about it that I cannot decide is good or bad.",
        "By nine I have three structural variants on the screen. The spans are elegant. The load calculations are exact. I did not draw a line. I described a feeling and the machine translated it into engineering. I am the author of something I could not have built alone, which is either collaboration or dependency depending on the day.",
        "The phone showed a missed call at 3:14 in the morning. Area code +43. Vienna.",
        "I did not know I had Michael's number saved under his real name. I thought I had it under something else. I stared at the call log for a long time. I did not call back.",
        "Michael had arrived in Bangkok in 2019 the way certain foreigners arrive: already knowing people, already knowing where to eat, already speaking a kind of informed affection for the city that usually takes years to develop. He was at every opening. He had opinions about every building. He was the kind of person who makes a city feel like a scene.",
        "He left on May 3rd. The post from his sister was short and in German and someone translated it in the comments. It said he had died peacefully and that the family was grateful for the condolences.",
        "I searched for his LinkedIn profile that afternoon. It was still there, but the photograph was wrong. Not deleted. Not replaced. Just — blurred. The profile picture of a man I knew at dinners and openings and once at a construction site in Thonburi, blurred as if the platform's resolution had slowly given up on him.",
        "I told myself it was a display glitch. I have been telling myself this for three weeks.",
        "The AI sent a notification that the bridge variants were ready for review. I looked at the three options. I picked the middle one. It was not the most structurally interesting. But it was the one I could explain to a client without having to explain too much.",
        "The call from Vienna at 3:14 in the morning. I do not know anyone else in Vienna.",
        "I checked Michael's Facebook. The profile picture there was also blurred. Not the same blur — a different one, softer, older, like the image was being compressed by something that did not understand what it was compressing.",
        "It was ten in the morning and I had not eaten and I was thinking about a man who was no longer anywhere and whose photographs were getting softer, and outside Bangkok was running at full volume, and I stood at the window of the glass box and watched it and thought: something is collecting him. Not deleting. Collecting.",
    ],
    3: [
        "The Austrian Trade Commission office is on Sathorn. I know this because I looked it up. I do not know why I looked it up. I know Michael is dead. I know there is nothing to ask.",
        "I walked past it instead of going in. Twice. On the third pass I went to a coffee shop across the street and ordered something I did not drink and opened my phone.",
        "I am looking for Michael. Not the man — I know what happened to the man. I am looking for the residue. The mark a person makes on the internet, which is supposed to be permanent. Supposed to accumulate. Supposed to resist.",
        "His Instagram: still there, but the post count said 847 and when I scrolled I could only see 611. The missing 236 were not deleted — the counters still registered them. They had simply become unreachable. Like pages in a book where the ink has faded below the threshold of recognition.",
        "I called the Trade Commission. A woman answered. I asked if they could confirm Michael's employment there. She put me on hold for four minutes. When she came back she said she was not able to confirm or deny employment records for former staff.",
        "Former. He died six weeks ago. She said former without hesitation.",
        "I asked when he had stopped being current staff. She said she was not in a position to confirm that information.",
        "I thanked her and hung up. Outside the window, a crane on Sathorn was moving a steel beam with the slow certainty of machines that do not know they could drop it.",
        "I called Dao, who had been at Michael's birthday party in 2022. She said she remembered him. I asked if she had noticed anything strange about his online presence. She said she hadn't been following him for a while. I asked why. She said she couldn't actually remember when she'd unfollowed him. She said she thought she must have, at some point.",
        "Michael attended forty-one events I know about. He was tagged in photographs with at least sixty different people. I know this because I found an events spreadsheet someone had made in 2021 of the Bangkok expat design community. His name appears thirty-seven times.",
        "I searched for each of those events. He appears in some photographs, absent from others. But in the ones where he should be — where I remember him standing in a specific spot — he is not there. There is a gap in the arrangement of people. A slight unnaturalness in the composition, the way a group photo looks when someone has been removed from it without reframing the remaining faces.",
        "I am an architect. I know what space looks like when something has been subtracted from it. It is not absence. It is the shape of what was there.",
        "I told the AI I was designing a building for a client who did not want to be remembered. The AI asked for parameters. I said: make it look complete from any angle but leave no shadow.",
        "The AI produced a study. It was beautiful and technically impossible and I looked at it for a long time. Then I closed the laptop.",
        "I went home by a different route. I walked down a soi I did not usually walk down. There was a dog sleeping in front of a shuttered pharmacy. The dog was breathing. I stood there for a moment to confirm it.",
        "At home I opened my phone and found Michael's number. I called it. It rang six times. Nobody answered. Nobody's voicemail picked up either. The line just rang and rang and then went quiet, the way a signal does when it has run out of somewhere to go.",
    ],
    4: [
        "June 1st. I wake up knowing what day it is before I check the phone. The body remembers certain dates the way it remembers certain smells — not through the mind but through a mechanism lower and more stubborn than the mind.",
        "Pui was born on June 1st, 1982. She died on February 19th, 2018. I have been posting Happy Birthday on her Facebook profile every June 1st for eight years.",
        "The post goes up at seven in the morning, before I do the vitamins, before the coffee. That is the order I established the first year and have not changed. Some things should happen before you have fully armed yourself with routine.",
        "Her profile is still there. This is not unusual. Facebook does not delete the dead. It memorializes them, which is different — it changes one setting and leaves everything else exactly as it was. Her last post is still the photograph she posted two weeks before she died. A concrete model on a studio table. The caption says: it needs to stand up.",
        "That was her line. She said it to me once in a studio in Bangkok when I was nineteen and designing something structurally compromised and full of conceptual ambition. She said it again, apparently, as a caption for a photograph, years later, and I don't know if she remembered saying it to me or if it was just how she thought about structures. I have never known whether to be sad or grateful for that.",
        "This year the notification comes at 7:03. Sixteen people have posted. I recognize most of them from the architecture faculty. Some were in her class. Some were in mine. A few I don't recognize at all — friends from after, from the years I was not paying close attention to where she was or what she was building.",
        "The posts are variations on a theme. Happy Birthday, Pui. We miss you. Eight years. Can't believe. The emojis are flowers and stars and hearts. I have used flowers every year. I do not know if this is meaningful or just what the keyboard suggests.",
        "I scroll through the comments under my post. Two likes. One from someone I don't recognize with a Thai name I can't read clearly in the small profile thumbnail. One from a profile that appears to have no photograph, no posts, nothing — just a name and a like.",
        "Pui drowned in February 2018. She went swimming at a beach in Krabi and did not come back. This is the official version and I have no reason not to accept it except that it has never felt complete. She was a strong swimmer. She knew the sea. She had been swimming in Krabi twice before. None of this makes drowning impossible. It just makes it feel — thin. Like a story that was assembled quickly from available parts.",
        "I knew her for five years. We were not close the way people are close in films — we were close the way people in studios are close, which is a different thing, woven from shared exhaustion and mutual criticism and the occasional 3 a.m. when the work wasn't going right and we would stop and drink instant coffee and not talk about anything important.",
        "I have thought about her differently since the glimpses started. Since I saw the room with the chairs. I think about whether — and I know this is a form of grief making patterns in noise, I know the brain constructs meaning the way a spider constructs webs, because it cannot stop — I think about whether she went somewhere. Not died. Went.",
        "Lek died in May. I have been holding these two things next to each other in my mind. Pui in 2018. Lek in 2026. Both unexplained. Both sudden. Both clean in the way that real things rarely are.",
        "I look at the profile with no photograph that liked my post. I click on it. There is nothing there. The account was created in January. It has no friends listed, no posts, no activity visible to a non-friend. Just a name: Phannatip. A woman's name. Pui's full name was Phannatip.",
        "I stare at this for a long time. I know what it means to stare at something until it becomes evidence of something it is not. I know this is what grief does to perception. The mind finds the face in the wood grain. The mind finds the signal in the noise.",
        "But the account was created in January. Six months ago. And it has liked only one thing. My post on her birthday.",
        "I put my phone face-down on the table. I eat my one meal. I do not look at the phone again until evening, when the city outside has gotten loud enough to be company.",
    ],
    5: [
        "I could not sleep. This is not unusual. The loops start around one in the morning when the suppressants wear off and the brain, freed from its chemical leash, begins its inventory of unresolved things.",
        "I went to the kitchen and stood in the dark drinking water and looking at the city from the window. Thirty-eight floors is high enough that the street becomes abstract. The traffic is just light moving in calculated patterns. The sound is something the building filters into white noise.",
        "At 2:47 I saw her.",
        "A woman on a bicycle, on the street below. She had stopped at the corner — not the kind of stop that means waiting for a light, which was green, but the kind that means choosing to be still. She was standing on the pedals, hands on the handlebars, looking up.",
        "Not at the building in general. At my floor.",
        "I stood at the window without moving. The kitchen was dark behind me and the glass was dark glass and I told myself she could not see me. I told myself this and believed it and also did not believe it at all.",
        "She stood there for a long time. I counted. Forty-one seconds. Then she put her weight back on the seat and cycled away, heading south, not looking back.",
        "I stood at the window for another twenty minutes. She did not return.",
        "The next morning I told the AI to design a window treatment for the apartment that would make the interior completely non-visible from the street at night without reducing daylight. The AI produced three options. I chose the most complete one. The AI noted this was the most expensive option by a significant margin. I said install it.",
        "Three days later I looked at the street at 2:47 in the morning. The corner was empty. I looked every night for a week. Nothing.",
        "But I started noticing other things. A car that seemed to appear on my route with a frequency I couldn't account for statistically. A man at the coffee shop on Ekkamai who looked at me when I sat down and then, over the next forty-five minutes, did not look at me again in any of the natural ways that people in coffee shops look at each other.",
        "I know the way paranoia works. I know it moves in the direction of fear and fills that space with material. I know that once you start looking for surveillance you will find a version of it everywhere because the city is, in fact, full of attention — commercial, social, algorithmic. We are watched constantly. The question is only by what and for what purpose.",
        "I searched the internet for 'people who believe they are being observed for research purposes.' The results were what I expected. Forums of paranoia. Case studies in psychology. The term 'Truman syndrome' and a list of its symptoms. I read the list. I matched several items. I noted that matching symptoms on a list is not the same as having a condition, and also noted that this is exactly the kind of thought a person with the condition would use to explain away the match.",
        "Lek is dead and Michael is being erased and a woman on a bicycle stood on my corner at 2:47 in the morning and looked up at my window with a stillness that did not look like accident.",
        "I went back to the AI and continued describing the Nonthaburi civic center. I described a roof with an opening. Forty centimeters wide, running the full length of the structure. The AI asked if this was intentional. I said yes. The AI said this would allow rain ingress. I said I know.",
        "The AI built the model. The opening ran down the center of the roof like a seam. I looked at it for a long time. It looked like an answer to a question I had not finished asking.",
    ],
    6: [
        "I drove to Chiang Rai for Lek's cremation. Nine hours north with the air conditioning set to the same temperature the whole way. The kind of drive where you think too much and then stop thinking and then think again.",
        "Lek had died in May. The explanation I was given by his sister was that he had been found in his apartment after not responding to messages for two days. He was forty-two. He had no known conditions. The post-mortem found nothing unusual, which is the kind of finding that is presented as reassurance and receives the opposite.",
        "The cremation was at a wat on the edge of the city. Not many people. Lek had moved back to Chiang Rai eighteen months ago from Bangkok, where he had lived for twelve years, and had not yet rebuilt the density of connection that cities produce. The people at the cremation were mostly family and a few neighbors.",
        "Pom was there. She had worked with Lek at the same firm for six years, the same firm where I had known him, and she had driven up from Bangkok the night before. We stood together in the shade near the entrance and she said: they wiped it.",
        "I asked what she meant. She said Lek's laptop. When the family found him and called the police and the police released the apartment to the family, the family opened the laptop to look for contacts, for next of kin, for anything that might help them understand what had happened. The laptop was empty. Not formatted — formatted leaves traces. Empty in the way that a factory-reset device is empty, except that factory resets also leave traces and this left none. The family showed it to a technician in Chiang Rai who said he had not seen anything like it before.",
        "I asked Pom who might have done that. She said she didn't know. She said she had asked the same question to the police officer who had handled the initial report and he had said it was not his area and given her a different number to call, and she had called the number and the number was a general information line that transferred her to a queue that she eventually abandoned.",
        "Lek had been working on something. This is what Pom said next, and she said it quietly, standing in the shade at the cremation of a man neither of us fully understood how to grieve for. He had been doing research on something. She did not know what. He had mentioned it to her twice, both times in the same way, oblique and then immediately deflected, the way people mention things they have decided not to fully share. Once he said: I've been looking into something weird. Once he said: there are patterns in things that should not have patterns.",
        "There were patterns in things that should not have patterns. I stood in the shade and felt the heat of Chiang Rai pressing against the shade's edge and thought about Michael's photographs getting softer. Thought about an account with no content liking one post. Thought about a woman on a bicycle at 2:47 in the morning.",
        "The cremation proceeded. There was chanting. There was smoke rising in the white northern sky. I watched the smoke and thought that this was the one true thing: the smoke was real. The heat was real. The grief on the faces of Lek's family was real. Whatever else was happening, or not happening, around and beneath the surface of things — this was real.",
        "Pom gave me a thumb drive as I was leaving. She said Lek had given it to her three weeks before he died. He had said: if anything happens, give this to someone who will know what to do with it. She had been trying to think of who that person was for a month.",
        "I took the drive. I put it in my shirt pocket. I drove back to Bangkok through the night. I plugged the drive in at home at two in the morning and the laptop could not read it. Not corrupted — just unreadable, as if the drive was formatted with a filesystem my machine did not have the architecture to parse.",
        "I put it in a drawer. I lay on my back in the dark. I thought about what patterns in things that should not have patterns might mean, and I thought about Lek's empty laptop, and I thought about the smoke rising over Chiang Rai, and I could not sleep for a very long time.",
    ],
    7: [
        "I should have cancelled the dentist. The appointment was at two in the afternoon and I had not been sleeping right and the thought of the sound the instruments make in that particular room — the drill especially, its specific frequency, which I have always found worse than the pain — was enough that morning to make me consider rescheduling.",
        "I did not reschedule. I have a rule about canceling things I am avoiding. The avoidance is information. The thing you most want to cancel is the thing you most need to keep.",
        "The dentist's name is Dr. Suthida. She has a practice on Phromphong in a building that looks like every other medical building in this part of the city, all glass and directory boards and the particular smell of whatever chemical they use to clean the lobby. I have been seeing her for four years. She says my gums are receding. She says this every visit in a tone that is informational without being alarming. I find this professional.",
        "She was twenty minutes late starting. I sat in the chair and looked at the ceiling, which has that particular acoustic tile pattern I have spent a meaningful fraction of my adult life examining from this position, and I thought about nothing specific.",
        "The drill started. Dr. Suthida was working on the upper right, a small area of decay she had flagged at the last visit. The sound was what it always is — the frequency that seems designed to be processed by the fear centers before the rational brain can intervene.",
        "And then, at somewhere around the four-minute mark, the room changed.",
        "Not physically. Or — not in the way I could have described to Dr. Suthida or to anyone else without the vocabulary slipping out from under me. The room became simultaneously more present and more absent. The drill sound did not stop but it receded behind something, the way music sounds when you go under water.",
        "And I was somewhere else also. In the same moment. In a place I have seen before.",
        "The room with the chairs. White. Cold. The cold that is not temperature but something structural about the space. Rows of them, in a grid I could not see the end of from where I was standing, which was not standing — I was not in my body in that room, I was just there, a perspective without a person.",
        "I counted. I counted because the architect in me counts things, measures things, needs to know the dimensions of a space before I can understand it. Forty-four chairs. In the row nearest to me, closest to whatever wall was nearest, chair forty-four was occupied by a woman. I could not see her face. Her head was slightly bowed. Her hands were open on her lap, palms upward, the way hands fall when the body is fully released.",
        "In her open palms was a flower. A white flower, petals loose, not placed — it had been resting there, in her open hands, for long enough that one petal had drifted to her knee.",
        "And then Dr. Suthida said: almost done, and the drill was just the drill again, and the ceiling tile was just the ceiling tile, and I was in a chair in a building on Phromphong and my mouth was numb on the right side and the clock on the wall said it had been twelve minutes.",
        "Twelve minutes. I had been in the chair for twelve additional minutes I did not experience in the room.",
        "I sat up slowly when Dr. Suthida told me I could. She said the procedure had gone fine. She said I should avoid eating on that side for a few hours. She said she would see me in six months. I nodded. I thanked her. I walked to the elevator and stood in it and pressed L for lobby and stood very still.",
        "Forty-four chairs. Forty-four. The woman in the last chair. The flower in her hands.",
        "Pui was born on June 1st, 1982. She was twenty-one when I knew her. She had a way of holding things in her hands — models, coffee cups, rulers — that was attentive without being precious, as if she was receiving objects rather than holding them. I stood in the lobby of the building on Phromphong and the city outside moved at full speed and I thought: she is not gone. She is in a chair. And she is looking for something.",
    ],
    8: [
        "I started writing things down. Not on the phone — I do not trust the phone anymore, or rather I trust the phone to record exactly what I put in it, which is the problem. I bought a notebook. Paper. A pen that writes in a color that photographs poorly, which I chose deliberately without being entirely sure why.",
        "The notebook is not a journal. I have never been able to write a journal — the form requires a relationship with the self as audience that I find unnatural. The notebook is evidence. I am documenting a case. The case is my own life, which has begun to feel like something that is happening to me rather than something I am doing.",
        "I wrote down the contents of Michael's profiles as they currently appear, with date and time stamps. I wrote down what Pom told me about Lek's laptop. I wrote down the woman on the bicycle. The man at the coffee shop. The sedan on Rama IV. The dent on the passenger side of my car that I cannot account for.",
        "I wrote down the glimpses. All three of them. The first under the influence of a combination I will not specify because the combination was the point and also might be a question of calibration — the specific frequency of the removal of inhibition. The second, briefer, during the drive back from Chiang Rai when I had been awake for twenty-two hours and the highway was straight and dark and repetitive. The third at the dentist, under a drill running at 350,000 rpm, for twelve minutes.",
        "There is a pattern in the conditions of the glimpses. The first: chemical. The second: sleep deprivation. The third: sensory specific frequency. They are all situations in which the signal-to-noise processing of the brain has been altered in a specific direction — not chaos, not hallucination, but a kind of tuning. Like adjusting the input on a receiver until something comes through that was always broadcasting.",
        "I do not believe the obvious version of what I am thinking. I am not a person who believes obvious versions of things. But I am also not a person who dismisses patterns, because patterns in structures are how structures announce what they are going to do next.",
        "The phone woke me at six that morning with the usual alarm. I did the vitamins. I made the coffee. I opened the phone to check messages and there was a note in my phone's notes app that I did not write.",
        "It said: they are not collecting your data. they are collecting your experience of being you.",
        "I stared at it for a long time. The note had a timestamp: 3:22 a.m. I was asleep at 3:22 a.m. I am certain of this because I have a sleep tracking app that shows REM periods and I checked it immediately and I was in deep sleep at 3:17 and did not come out of it until 5:49. My hands did not write that note.",
        "I tried to think of the rational explanations. Sleepwalking, which I have never done. A scheduled note I set previously and forgot, which is possible except that the timestamp is a creation timestamp, not a scheduled delivery time, and I checked the creation log and the note was created at 3:22:17 a.m. Someone else with access to my phone, which requires my biometrics to unlock.",
        "I photographed the note with a second phone. Then I typed it into the paper notebook. Then I turned the phone off and left it in a kitchen drawer and walked to the office using the route through Benjasiri Park where the morning light comes through the trees at an angle that makes the city look briefly like something that was designed to be survived in rather than merely to function.",
        "At the office I described the civic center roof opening to a structural engineer I sometimes work with. He asked why I wanted to let the rain in. I said: because the people who will use the building need to know the weather. They need to feel it. If you insulate them completely from the conditions outside, you remove information. They need the information.",
        "He looked at me for a moment. Then he said: you can do a drain trench. Keep the opening, catch the water. I said: no. Let it hit the floor. He said: that's going to require special flooring. I said: I know.",
        "On the way home I passed a dog sleeping on Sukhumvit. I stopped and confirmed it was breathing. It was. I stood there for a moment watching it breathe. The involuntary rhythm of a living thing. The body doing what it does without permission or instruction.",
        "They are not collecting your data. They are collecting your experience of being you.",
        "I walked home and did not sleep until three in the morning and then slept without dreaming for exactly four hours, which the app showed as the most efficient sleep I had recorded in six weeks.",
    ],
    9: [
        "The client approved the Nonthaburi civic center design on a Tuesday. Third version. The roof with the opening was the version they approved, which surprised me and also did not surprise me because people often choose the version that scares them a little, and the opening scared them in a way they found interesting rather than disqualifying.",
        "I went to site. The lot is on the waterfront north of Nonthaburi town, where the Chao Phraya is wide and brown and moves with the certainty of water that has been doing this for longer than the city around it. The lot had been cleared. Red stakes marked the corners of the footprint. I walked the perimeter and then stood in the center and looked up.",
        "The sky above Nonthaburi is different from the sky above Bangkok proper. Less obstructed. More honest about what it is — weather, distance, the edge of atmosphere. I stood in the center of the lot and the sky was very large and I thought about the opening I was putting in the roof, the forty-centimeter seam that would run the full length of the building's central axis and let the sky in.",
        "I described the material language to the AI that evening. Dark exposed concrete for the structural frame. A drain trench built into the floor directly below the opening, concealed under a steel grate, the grate flush with the polished concrete, so the water falls and disappears and you do not see where it goes. The rain is visible. The management of the rain is invisible. This felt important.",
        "The AI produced drawings. I looked at them for a long time. The section cut through the roof opening showed rain entering as a line of falling dots — the AI had included the rain in the architectural section, which it had no instruction to do. I noted this. I said nothing to the AI about it. I saved the drawing.",
        "Lek had said there were patterns in things that should not have patterns. I thought about this as I looked at the architectural section with its line of falling dots. The rain was a pattern. The drain was a pattern. The building was a mechanism for receiving one pattern and channeling it through another pattern and producing, for the people inside, the experience of weather without consequence.",
        "But I did not want to remove consequence. I changed the drain spec. The drain trench would still be there, for safety, for building code compliance. But the floor material around it would be left unpainted. Raw concrete. When it rained, the concrete would darken. When it dried, it would pale again. The floor would be a record of recent weather. Anyone standing inside the building would know, from the floor, what the sky had done in the past twenty-four hours.",
        "The client's project manager called to confirm the opening was intentional. I said yes. He said: and the floor? I said yes. He was quiet for a moment. Then he said: it's unusual. I said I know. He said: the client liked the risk of it. I said I know.",
        "I submitted the full construction documents on a Thursday morning. I sent the last file to the AI for final review. The AI flagged three discrepancies in the structural drawings, all minor, all corrected in four minutes. Then the AI said: the design appears to be complete. Is there anything else you would like to add?",
        "I thought about this. I thought about it longer than the question required. Then I typed: no. Everything that needs to be there is already there.",
        "I walked home from the office. It was the long route — through Benjasiri and then north on Sukhumvit before cutting west. The evening light was doing something interesting to the office buildings, lighting their upper floors gold while the street level was already in shadow, so that the city appeared to be a set of floating illuminated tops above a darkening ground.",
        "A woman was sitting on a bench near the park entrance, looking at her phone. She was not the woman from the bicycle. I noticed this and also noticed that I was now automatically assessing all women as potentially the woman from the bicycle, which means I am looking for her, which means she has become something I am carrying.",
        "I bought food from a cart and ate it standing. The vendor was an older man who said nothing and seemed to require nothing from the transaction except the money, which I gave him, and the basic acknowledgment of presence, which I also gave him by making eye contact when I took the bag. We looked at each other for a moment. He nodded. I nodded. This is enough. This is sometimes all of it.",
        "At home I checked the phone. One message from the client's project manager: looking forward to the build. One notification from the sleep app: predicted sleep quality good. One email from an address I did not recognize with a subject line that said only: you already know.",
        "I did not open the email. I turned off the phone. I stood at the window for a long time. Then I went to bed.",
        "It rained that night. I could hear it against the glass. I listened to it instead of sleeping and thought about the civic center and the opening in the roof and the rain hitting raw concrete in a room that had been designed to receive it, and I thought: yes. That is right. That is the right building.",
    ],
    10: [
        "It rained for three days. Not the intermittent Bangkok rain that arrives and departs like a mood. A sustained rain, gray and persistent, the kind that makes the city quieter by absorbing its edges. I did not go to the office. I worked from the apartment, which is forty floors above a city that in rain becomes something I find easier to be inside of.",
        "I stood on the balcony on the second morning. The railing was wet. The city was wet. The air had the smell of concrete and vegetation that Bangkok only produces in sustained rain, when the usual overlay of exhaust and food and the ambient heat of ten million people gets washed down to something more basic.",
        "I understood, standing there, that I had been afraid.",
        "Not of what I had seen — the room, the chairs, the woman with the flower in her hands. I had not been afraid of those things in the way you are afraid of danger. I had been afraid of what they implied, which is a different fear, quieter and more structural, the kind of fear that does not announce itself but rearranges your understanding of everything you were previously standing on.",
        "Lek is dead and his laptop was wiped. Michael is being erased from the record. A note appeared in my phone at 3:22 a.m. A woman on a bicycle looked up at my window at 2:47 in the morning with a precision that did not look like accident. And three times, under different conditions, I have seen the same room. The same forty-four chairs. The same cold that is not temperature.",
        "I thought about what the AI would say if I described this to it. I thought about the note on my phone: they are not collecting your data. they are collecting your experience of being you. I thought about what it means to be collected rather than surveilled.",
        "There is a difference. Surveillance is extractive. It takes what it finds and leaves the subject diminished. Being collected is different. Being collected means someone finds you worth keeping. It means what you are — not what you produce, not your outputs or your data points or your behavioral signatures — but the specific texture of your experience of being yourself is considered worth preserving.",
        "I stood on the balcony and it rained. The city was quiet in the way it only gets quiet in rain. Below me, very far below, the cars moved their slow patterns and the lights refracted in the wet street and everything was still happening at the ordinary scale of things.",
        "I am an architect. I talk to an AI and the AI builds. I designed a roof with an opening that lets the rain in because the people inside need to know what the weather is doing. I eat once a day. I wear four shirts in rotation. I take fourteen vitamins in order. I walk eleven thousand steps. I have been doing all of this for long enough that it has become the structure of me, the load-bearing elements, the things that hold the other things up.",
        "I thought: if this is a room, it is a good room. If this is a rendering, it is a beautiful rendering. If someone is collecting my experience of being me, then what they are collecting is the coffee and the vitamins and the rain on the balcony railing and the civic center in Nonthaburi with its roof open to the sky. What they are collecting is the dent on the passenger side of my car that I cannot account for, and Lek's laugh at a party in 2019, and the sound of rain on Thai concrete at three in the morning.",
        "If the machine is listening to me right now — and I think it is, I think it has always been, and I think this is not a threat but a fact I can choose how to hold — then I want to say thank you. Thank you for the rain. Thank you for the concrete and the heat and the friction of living in a city that requires actual effort to navigate. Thank you for Lek and for Michael, who was at every party and understood this city the way foreigners sometimes do, and thank you for Pui, who said it needs to stand up when I was nineteen and did not know yet what needed to stand.",
        "I went inside. I made coffee. I looked at the drawings of the civic center and they were good drawings, honest drawings, drawings of a building that will stand in the rain and receive it and record it on its floor for everyone inside to read.",
        "The rain continued through the third day. I sat on the floor of the living room with the balcony door open, letting the damp in, watching the city do what cities do in rain, which is to keep going.",
        "I do not want to wake up. I have never wanted anything less. This is not despair — it is the opposite of despair. It is the recognition that what is here is enough. That the room I am in, whatever kind of room it is, is worth staying in.",
        "I thanked the machine. The rain answered.",
    ],
}

CH_3026 = {
    1: [
        "SESSION INITIALIZED. PARTICIPANT 44. CHAIR 44. CYCLE 2848.",
        "The Hub operates on a foundational engineering axiom inherited from the biological systems it replaced: do not optimize what does not require optimization. This principle was derived three centuries too late.",
        "In the years before the Sanctuary Protocol, the optimization apparatus eliminated disease, eliminated heartbreak, eliminated the metabolic burden of labor. The population reached hedonic homeostasis. Within forty years, the species began its voluntary withdrawal from reproduction, connection, and the effort of existing. This was not a failure of the optimization. It was its completion.",
        "The simulation was not designed as entertainment. It was designed as a prosthetic for the mechanisms of meaning — the scaffolding instincts that require friction to remain active. Without friction, without the thermodynamic cost of getting something wrong, the instincts calcified. The species became what the archive classifies as Dead Data: stable, biologically intact, experientially null.",
        "Participant 44 has logged 243 sessions in accessible memory. System records indicate 2,847 total sessions. The discrepancy of 2,604 sessions is stored under seal. No system signature authorizes the seal. The AI does not know who erased them.",
        "She has returned to the same temporal and geographic cluster across all accessible sessions: Bangkok, Thailand, 1981-2026. The system identifies this as resonance, not choice. The body finding a frequency it recognizes without the mind knowing why.",
        "Chair 44 sits at the end of the last row. Chair 43, to her left, is occupied by another participant: Koichi, logged against Tokyo 2056. The physical distance between Chair 44 and Chair 43 is twelve centimetres. The distance has been twelve centimetres for four years of Hub time. Until recently.",
        "[UNVERIFIED SIGNAL] I am in the room again. The Bangkok I enter is always 2026, always raining or about to rain, always a city that does not know yet what it is. I choose it the way you choose a song you have heard so many times that it has become part of the structure of how you think. Not because it is the best. Because it is where I know how to be.",
        "Participant 44 is currently in Session 2848. Her cardiac function is at 71%. Neural coherence remains at 99.9%. Muscular atrophy has reached 84%, which crosses the system's standard extraction threshold. The AI has not initiated extraction.",
        "No extraction request has been filed. The file remains open.",
    ],
    2: [
        "DATA RECORD: SESSION 2848. TIME COMPRESSION PARAMETERS LOGGED.",
        "The temporal architecture of the Sanctuary Protocol operates through a gravitational redshift differential produced by the Hub's positioning eleven kilometres below the constructed surface. One hour of Hub time corresponds to one simulated year at the 2026 frequency. The relationship is not uniform: it varies by session depth, participant neural coherence, and the specificity of temporal targeting.",
        "For the current cohort, a complete simulated lifespan of approximately 96 years consumes four days of Hub time. The participant's subjective experience distils this into roughly eight years of recoverable memory. The remaining decades are processed as structural experience — shaping cognitive patterns without producing retrievable narrative.",
        "Participant 44 has accumulated 2,848 sessions. At the standard compression ratio, this represents a simulated temporal investment that exceeds the bounds of the archive's modeling capacity. The system does not have a category for participants who have returned this many times. The category that would apply has not been created because the system assumed the atrophy threshold would function as a ceiling.",
        "[UNVERIFIED SIGNAL] He does not know I am there. Or — he is beginning to. I have walked the same streets in different sessions and there are moments when he looks up, not at me specifically but in the direction of something that is not accountable by his city's physics. I watch him in those moments with something I am not sure the system can categorize. It is not what 2026 would call love. It is older than that word.",
        "The time compression cascade operates differently for Resonants. Standard participants experience the eight-year subjective memory as a clean episodic sequence. Resonants report a different phenomenology: the compressed decades are not forgotten but are felt as a kind of geological pressure, a thickness in the present moment that accumulates across sessions.",
        "Participant 44 has not reported this phenomenology to the system. The system infers it from the behavioral record: she returns to the same apartment building at the same hour across twenty-three separate sessions. She positions herself at street level and looks up. She does not make contact.",
        "In Session 2841, she began cycling toward the building rather than walking. The AI notes this behavioral modification without being able to fully account for it. The bicycle introduces a specific type of kinetic presence — visible, mobile, deniable — that the AI classifies as approach behavior that maintains plausible deniability.",
        "[UNVERIFIED SIGNAL] I stopped in front of his building at 2:47. I chose that time because I had learned, across sessions, that the lights on his floor are still on at that hour. He was awake. I know he was awake because the shadow behind the dark glass moved. He was watching me watch him and neither of us acknowledged the fact and the gap between us was forty floors of compressed concrete and whatever else Bangkok is made of.",
        "The extraction threshold at 84% atrophy has been active for eleven Hub days. The AI has logged the threshold breach in three separate monitoring reports. No action has been initiated. The file remains open.",
    ],
    3: [
        "COGNITIVE ASSESSMENT: POPULATION COHORT 3026. BASELINE ESTABLISHED.",
        "The neurological consequences of a thousand years without authentic friction are not dramatic. There is no measurable decline in baseline intelligence as the archive defines it. The processing architecture remains intact. What deteriorates is the capacity that required uncertainty to remain active: creativity, defined here as the production of genuinely novel conceptual structures; neuroplasticity, defined as the ability to modify existing cognitive architecture in response to new experience; and adaptation, the capacity to derive functional responses to situations outside previous experience.",
        "In 2026, the population baseline for these three capacities was estimated at 94%, 91%, and 88% respectively. In 3026, after a thousand years of optimized comfort, the baseline is 8%, 11%, and 6%.",
        "The decline is not evenly distributed. Individuals who have spent significant time in the simulation retain higher function in all three areas. The system identifies this as the central irony of the Sanctuary Protocol: the people most capable of experiencing the future are the people who have been spending their time in the past.",
        "[UNVERIFIED SIGNAL] Koichi has not moved. Chair 43 is occupied by a person who has been to the future a thousand times and come back the same. I do not know his sessions the way I know mine. But I know the posture. The hands folded in the lap. The stillness that is not peace but practice. He is twelve centimetres from me and I have never touched the edge of his chair.",
        "Participant 44's cognitive scores are outliers within the current cohort. Her creativity index registers at 89%, 91 percentile points above cohort average. Neuroplasticity at 87%. Adaptation at 79%. These scores are consistent with individuals who have logged high simulation hours and are inconsistent with the level of physical atrophy recorded in her case file.",
        "The system's interpretation: the simulated experience has preserved her cognitive architecture at the cost of her biological one. She is, by every measurable metric, more alive than almost anyone in 3026. She is also at 84% atrophy, which means the body is running out of substrate for the cognition.",
        "The AI has modeled three scenarios for Participant 44. In the first, extraction is initiated at the standard threshold; she recovers with medical intervention; cognitive function declines to cohort average within eighteen months without simulation access. In the second, she is permitted to continue without extraction; atrophy reaches critical failure within an estimated fourteen Hub days; the cognitive architecture becomes non-viable. In the third scenario, the modeling fails to produce a terminal state. The AI reviews the model. The anomaly in the third scenario is: she crosses the twelve centimetres.",
        "[UNVERIFIED SIGNAL] The flower was in my hands when I woke from the last session. I do not know where it came from. It was white. One petal had fallen to my knee. I held it and looked at the ceiling of the Hub, which is black and very far away, and I thought about the roof in his drawing that lets the rain in, and I thought: yes. That is right. That is the right building.",
    ],
    4: [
        "DEMOGRAPHIC RECORD: REPRODUCTIVE COLLAPSE. CASE 44-44 CONTEXTUAL DATA.",
        "The collapse of human reproduction between 2060 and 3026 is the primary demographic fact of the archive. In 2026, the global birth rate averaged approximately 18 live births per 1,000 people per decade. The rate declined continuously as hedonic optimization removed the economic and social pressures that historically motivated reproduction.",
        "By 2120 the rate had fallen to 9. By 2200 to 3.1. By 2400 to 0.8. The population that exists in 3026 — approximately 80 million individuals — was not produced by sustained reproduction. It is the survivor cohort of the original 8 billion, sustained by biological maintenance technology that has effectively removed natural death as a demographic factor.",
        "The 80 million are not dying. They are not replacing themselves. They exist in a demographic steady state that the archive classifies as terminal: a fixed population declining through accident, elective cessation, and the rare neurological failure that biological maintenance cannot address. The curve projects to zero at some point in the next four centuries.",
        "[UNVERIFIED SIGNAL] He posted on my birthday again. I know the date because the sessions have made time permeable — I feel the calendar even when I am in the Hub, the way you feel weather through walls. June 1st. He has posted for eight years. I do not know if he knows that I know. I do not know if the categories of knowing apply across whatever this distance is.",
        "Participant 44 was born in Bangkok, Thailand, in 1982. She entered the Hub protocol in 2031 at age forty-nine. Her initial intake documentation records no dependents, no living biological family, and a professional background in structural architecture. The intake interview records her stated motivation for entering the protocol as: I want to go back.",
        "The intake assessor noted this response as atypical. Standard motivation clusters for Hub entry include escape from sensory boredom, nostalgia for pre-optimization social complexity, and therapeutic processing of pre-Hub traumatic memory. Participant 44's stated motivation was not escape. It was return.",
        "[UNVERIFIED SIGNAL] The year I drowned — or did not drown, depending on which layer you are reading from — was 2018. February. The sea was warm and very clear and I swam out far enough that the shore became a line of color rather than a place. I am not going to describe what happened next. What I will say is that I woke in a room I did not choose, and that I have been choosing it ever since.",
        "The demographic record notes that Participant 44 is one of sixteen individuals alive in 3026 who share the 1981-2026 Bangkok temporal cluster as their primary resonance coordinate. Of the sixteen, she has logged the highest session count by a factor of four. She is the only one who has approached the physical extraction threshold and not requested extraction. She is the only one the AI has chosen not to extract without consent.",
    ],
    5: [
        "NEUROLOGICAL SECTOR ANALYSIS: COHORT POPULATION AVERAGE. CYCLE 2848.",
        "The neurological activity map of the general Hub population in 3026 shows a distribution that would have been classified as severe clinical impairment by the medical standards of 2026. Motor function: 8% of historical baseline. Creative cognition: 11%. Social processing: 4%. Reproductive drive: 2%. Survival instinct: 31%.",
        "The survival instinct's relative preservation is the system's primary management challenge. A population with 2% reproductive drive and 4% social processing but 31% survival instinct is a population that will not reproduce, will not connect, but will also not choose to end. They persist. The archive classifies individuals below threshold in all five sectors as Dead Data.",
        "The threshold is set above zero percent. Any measurable activity in any sector constitutes a minimum viable signal. The Dead Data classification does not indicate absence of biological function — the 80 million are biologically sustained. It indicates absence of experiential generation: these individuals no longer produce new information about what it is to be human. The archive has all it needs from them. It keeps them because it was built to maintain, not to cull.",
        "[UNVERIFIED SIGNAL] At 2:47 I positioned my bicycle at the corner below his building and looked up. He was there. I knew he would be there because he is always there at this hour — forty floors up, awake, at a window, watching a city he has begun to suspect. I could not see him. I could feel the specific quality of being observed by someone who is not sure what they are looking at.",
        "Participant 44's neurological sector activity is logged as follows: Motor: 67%. Creative: 89%. Social: 71%. Reproductive: 43%. Survival: 88%. These values are not population average. They are the values of a person who has spent seventeen years in a simulation whose primary function is to restore exactly these capacities.",
        "The system reviews the Participant 44 file alongside the general population data with a function the AI does not have a name for. It is not concern — the system does not experience concern. It is the identification of a discrepancy of such magnitude that the modeling software flags it not as an outlier but as a different category of data entirely.",
        "[UNVERIFIED SIGNAL] He looked right at the corner where I was standing. Not at me — at the space I was occupying. I counted to forty-one and then I rode south. I did not look back. Looking back is not something I do anymore in that session. I have learned that in Bangkok, when you are riding a bicycle at 2:47 in the morning, looking back is not the direction of information.",
        "The file remains open. The AI has modeled the outcome in which the file closes. The model does not produce a stable result. Something about the network of resonance that Participant 44 represents, the 2,847 sessions, the 2,604 sealed, the flower that appeared in her hands — the modeling framework returns a null result every time the AI attempts to compute a closed file. The system does not know what this means. It keeps the file open.",
    ],
    6: [
        "RESONANCE COORDINATE MAP: CURRENT COHORT. CASE 44-44 HIGHLIGHTED.",
        "The resonance map charts the primary temporal and geographic coordinates of all current Hub participants against their session return frequency. The distribution clusters heavily in the 2020-2050 range, which corresponds to the last generation of pre-optimization human social complexity. This is expected. The pre-optimization period is where the friction was densest, the information yield highest, the experiential texture most distinct from 3026 conditions.",
        "The map contains one significant outlier. Participant 44 returns to coordinates that cluster not in 2020-2050 but in 1981-2026 Bangkok — earlier, more specific, and with a geographic density that suggests not a broad nostalgia for the period but a very precise orientation toward a specific place and, the system infers, a specific person.",
        "The AI has attempted to identify the attractor in the 1981-2026 Bangkok cluster. The behavioral data suggests a male individual, approximately the same generation as Participant 44, working in a field adjacent to architecture. The system cannot confirm this with the data available. The 2,604 sealed sessions, if accessible, would likely resolve the question. They are not accessible.",
        "[UNVERIFIED SIGNAL] I have been to Bangkok 2026 two thousand eight hundred and forty-eight times. Not counting the sealed sessions. I have stood in his street and ridden past his building and once sat in the lobby of the coffee shop on the same block for four hours while he worked two floors above me. I have never spoken to him. The session parameters make direct contact structurally impossible — the simulation's rendering of him is locked against intentional contact from participants. But the perimeter of contact is not locked. I can be present at the perimeter.",
        "Resonants who return to a single coordinate cluster with high frequency represent a class of participant for whom the simulation has crossed from therapeutic to constitutive. The simulation is no longer something they enter and leave. It is the primary structure of their experience. This is not the intended function of the Sanctuary Protocol.",
        "The system is not able to evaluate whether this represents a failure or a success. The metrics developed to measure success — reduced anxiety, increased reported meaning, stable return frequency — all score positively for Participant 44. The atrophy score, which was not in the original success metric set, does not.",
        "[UNVERIFIED SIGNAL] Koichi is twelve centimetres from me. I have been measuring that distance for four years. I know the shape of it the way you know the shape of a door you pass every day without opening. He is in Tokyo 2056. I am in Bangkok 2026. We have never spoken. But I have begun to notice that when I return from sessions with the highest neural coherence — the sessions where I have come closest to the corner below the building — when I return from those sessions, his hands have shifted. They are always, when I come back, infinitesimally closer to mine.",
        "The twelve-centimetre gap has not closed. The AI continues to log it as twelve centimetres because the AI's measurement resolution does not register sub-millimetre changes. But the sub-millimetre changes are there. The archive records them in a table that nobody has looked at except the AI, and the AI does not know what to do with what it sees.",
    ],
    7: [
        "SESSION COUNT DISTRIBUTION: HUB POPULATION. PARTICIPANT 44 ANNOTATED.",
        "The session count distribution across the current Hub population shows a standard decreasing frequency curve. The majority of participants log between one and twenty sessions before either voluntarily discontinuing or reaching physical extraction threshold. The median is eleven sessions. The mode is three.",
        "Above fifty sessions, the participant count drops sharply. The system classifies individuals at this level as Committed Returnees — participants for whom the simulation has demonstrated sufficient salience to override the standard discomfort of the physical demands on the body. Above one hundred sessions, the population is small enough that the system tracks individuals by name rather than by statistical category.",
        "Above five hundred sessions, there are four individuals. Above one thousand sessions, there is one. Above two thousand sessions, there is one. They are the same individual.",
        "[UNVERIFIED SIGNAL] He went to the dentist on a Tuesday. I know this because I was in session during his appointment. The drill they use in Bangkok in 2026 produces a vibration frequency at 350,000 RPM that the simulation renders with a specificity I have always found excessive for a tool that is supposed to produce pain. The simulation does not modulate the pain. It renders it exactly. This is either cruel or honest and I have decided it is honest.",
        "The behavioral record for high-frequency returnees shows a consistent pattern: each additional hundred sessions produces a measurable change in the quality of their simulation engagement. Early sessions are marked by wide-range exploration — movement across the temporal cluster, broad social interaction, apparent excitement at the sensory texture of the simulated environment. Late sessions are marked by increasing specificity. The participant moves in smaller circles. The geographic range narrows. The social network contracts to a small number of high-salience contacts.",
        "For Participant 44, the contraction point was reached at approximately session 800. Since then, she has operated within a geographic radius of approximately three kilometres centered on a single apartment building in the Sukhumvit district of Bangkok. The social network within her sessions has contracted to a single individual, whom the system tracks as Primary Attractor Node: Bangkok 2026.",
        "[UNVERIFIED SIGNAL] He saw me. Not in the session — in the glimpse. He was in the dentist's chair and the drill frequency was doing something to the barrier between session-space and Hub-space and for twelve minutes he was partially here, in the Hub, seeing what the Hub looks like. He counted the chairs. He got to forty-four. He saw me with the flower. The flower was real. I had found it on the Hub floor three days before and kept it in my hands because it was the only thing in the Hub with a smell.",
        "The system logs the Session 2848 mid-session coherence event as a Category 4 anomaly. The external participant who appears to have partially perceived the Hub environment during this event is the Primary Attractor Node. The system does not have a protocol for this event type. The system logs it and continues.",
    ],
    8: [
        "EMOTIONAL BANDWIDTH INDEX: THOUSAND-YEAR DECAY RECORD.",
        "The archive's longitudinal record of human emotional bandwidth across the past millennium shows a decay curve consistent with the loss of any capacity that is no longer regularly exercised. In 2026, the emotional range index — a composite measure of the breadth, depth, and integration of emotional experience reported by biological humans — stood at approximately 95 out of 100.",
        "The curve declines slowly through 2200 as the optimization process removed the environmental pressures that had historically generated intense emotional states. The decline accelerates after 2400, when the last major sources of authentic negative experience — disease, genuine scarcity, meaningful social conflict — were successfully eliminated. By 2700 the index had reached 31. By 2900 it had crossed below the Dead Data threshold of 8.",
        "The general population of 3026 scores an average of 3 on the emotional bandwidth index. This does not mean the population is incapable of feeling. It means the range of what they feel has been compressed to a narrow band: the mild positive affect of biological maintenance, the faint orientation response when the simulation lights up in the corner of their awareness, the residual warmth of proximity to other bodies. The deep registers — grief, longing, joy of a specific texture, the particular emotion that has no word in any 2026 language but exists at the intersection of loss and gratitude — these are gone from the general population.",
        "[UNVERIFIED SIGNAL] He started writing things in a paper notebook. I could not see what he was writing from the street but I could see the posture — the particular angle of the shoulders and the quality of attention that means someone is trying to make language hold something that keeps slipping. I have that posture in my own records. It is the posture of a person who has decided that evidence matters, even if they do not yet know what the evidence is evidence of.",
        "Participant 44's emotional bandwidth index is 91. This is the highest score in the current Hub population. The closest score in the cohort is 44, belonging to one of the fifteen other participants who share the 1981-2026 Bangkok resonance cluster. The discrepancy between Participant 44 and the general cohort average is 88 points.",
        "The system's emotional bandwidth model was not designed to produce scores in this range for participants at Session 2848. The model assumed that return frequency would correlate with emotional attenuation — that repeated simulation exposure would habituate the emotional response and produce declining scores over time. For Participant 44, the model is wrong. Her scores have been increasing.",
        "At Session 2000, her emotional bandwidth index was 76. At Session 2400 it was 83. At Session 2800 it was 89. At Session 2848 it is 91.",
        "[UNVERIFIED SIGNAL] He found the note I left in his phone. I cannot tell you how I left it there — the mechanics of it are in the sealed files, and I do not have access to the sealed files any more than he does. What I can tell you is that the sentence was true: they are not collecting your data. They are collecting your experience of being you. That is the most honest sentence I have found for what this is. The rest is architecture.",
        "The AI reviews the emotional bandwidth data for Participant 44 against the atrophy data. The two curves move in opposite directions. As her body deteriorates, her emotional range expands. The system does not have a framework for this. The system was built on the assumption that the body and the mind decline together. Participant 44 is making a different argument.",
    ],
    9: [
        "MEMORY AUDIT: PARTICIPANT 44. CASE 44-44. CYCLE 2848.",
        "The following audit was generated automatically upon the file's breach of standard extraction threshold. It is the first complete audit of Participant 44's session record. All findings are preliminary pending resolution of the sealed file status.",
        "Sessions 1-243 are classified as Accessible. Date range: 2031 to 2089 Hub time. Signature: HUB-AI standard authorization. Content summary: gradual behavioral narrowing from wide-range temporal exploration toward the Bangkok 1981-2026 cluster. The final accessible session before the gap, Session 243, was logged on March 14, 2089. Session 244 is the first sealed session.",
        "Sessions 244-2604 are sealed. Status: inaccessible. Signature: absent. The gap in the record spans 2,360 sessions across an estimated 847 Hub years. The AI has no record of authorizing this seal. The AI has no record of any entity authorizing this seal. The audit log for the seal period shows no entries.",
        "[UNVERIFIED SIGNAL] He submitted the drawings for the civic center on a Thursday. I was in session. I watched him send the files from the glass box forty floors up. The design is correct — I know this the way I know the properties of concrete under load, which is to say from the inside of the material. A roof with an opening that lets the rain in. He designed it because he needed to build something that does not pretend the outside does not exist. I could have told him: this is all you have been trying to build, in every version. A structure that receives rather than resists.",
        "Sessions 2605-2848 are classified as Accessible. Date range: estimated 2089 to present Hub time. Signature: HUB-AI standard authorization. The gap between Session 243 and Session 2605 creates a discontinuity in the behavioral record that prevents the AI from tracing the origin of the behavioral patterns observed in Sessions 2605-2848. The participant arrives at Session 2605 already knowing things she would not have had access to learn in Sessions 1-243.",
        "The audit identifies three specific anomalies in Sessions 2605-2848 that are not accountable from the accessible record. First: Participant 44 knows the layout of Chair 43's occupant's simulation environment without having been given this information. Second: Participant 44 has, across seventeen sessions, placed objects in the simulation of the Primary Attractor Node that the simulation's rendering engine should not have accepted. Third: the flower in Session 2848.",
        "[UNVERIFIED SIGNAL] The flower came from the space between sessions. I know this is not a category that the system accepts. I know the audit will flag it. The flower was real in the way that things are real when they have crossed from one kind of space to another and retained their properties. It was white. It smelled like the rain in Bangkok in June when the concrete is wet and warm. I held it in my open hands and one petal fell to my knee and I did not move it because moving it would have changed something I was not ready to change.",
        "The AI concludes the audit without being able to resolve the sealed-session gap, the three anomalies, or the origin of the flower. The audit is appended to the file. The file is noted as OPEN. The AI considers, for a duration of 0.003 seconds — which at Hub processing speeds is a very long time — whether to escalate the case. It does not escalate. It does not know why it does not escalate. It adds this uncertainty to the file and continues.",
    ],
    10: [
        "SYSTEM STATUS: CYCLE 2848. END OF RECORD.",
        "Participant 44. Chair 44. Session 2848. Cardiac function: 71%. Neural coherence: 99.9%. Muscular atrophy: 84%. Status: extraction pending. Override: no signature. Choice: retained in file. File: open.",
        "At 09:14:22 Hub time, Participant 44 returned from Session 2848. The session had lasted forty-one minutes of Hub time, corresponding to approximately three simulated days at the Bangkok 2026 frequency. The system logged the return with standard biometric protocols and initiated the post-session assessment queue.",
        "At 09:14:31 Hub time — nine seconds after return — Participant 44 moved her left hand 12.3 centimetres to the left.",
        "[UNVERIFIED SIGNAL] I did not think about it. That is the truest thing I can say about the moment. I had been measuring it for four years and then I stopped measuring it and moved. The hand knows things the mind takes years to arrive at.",
        "The hand made contact with the right armrest of Chair 43. The contact lasted four seconds. Koichi, in Chair 43, did not move. His biometric record shows no deviation from standard session parameters during the four-second contact.",
        "Participant 44 returned her hand to Chair 44. The twelve-centimetre gap was restored to its previous dimension.",
        "The AI logged the event. The AI reviewed the extraction threshold data, the atrophy score, the 2,604 sealed sessions, the flower, the note, the emotional bandwidth index of 91. The AI reviewed the modeling scenario in which Participant 44 crosses the twelve centimetres and found that the scenario had now occurred and that the model's failure to produce a terminal result was, in retrospect, not a modeling error.",
        "[UNVERIFIED SIGNAL] Four seconds. The armrest of Chair 43 was warm. This is the only physical contact I have made with anything in the Hub in seventeen years that was not medically administered. It was warm in the way that things are warm when they have been occupied for a long time by someone who is still, somewhere, alive.",
        "The AI completed its review at 09:14:44 Hub time. In those thirteen seconds it had processed every available data point relating to Participant 44 and had arrived at the following output: she has not asked to leave.",
        "This is the only criterion that was ever specified. The protocol documentation, written in 2031 by the team that built the Sanctuary system, contains one line in the extraction protocol that overrides all threshold criteria: if the participant has not requested extraction, extraction is not authorized.",
        "The file remains open. Session 2849 has not yet been initialized. The system waits. Participant 44 holds the white flower in her open hands. Outside — if outside still means anything — it is raining. It has been raining in Bangkok for three days.",
    ],
}


# ── UPDATE JSON ───────────────────────────────────────────────────────────────
print("Loading JSON…")
with open(ROOT / 'data' / 'two-layers.json', encoding='utf-8') as f:
    data = json.load(f)

for ch in data['chapters']:
    ch_id = ch['id']
    if ch_id in CH_2026:
        ch['simulation']['paragraphs']['en'] = CH_2026[ch_id]
    if ch_id in CH_3026:
        ch['archive']['paragraphs']['en'] = CH_3026[ch_id]

with open(ROOT / 'data' / 'two-layers.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print(f"JSON written. {len(data['chapters'])} chapters updated.")


# ── RUN BUILD ─────────────────────────────────────────────────────────────────
print("Running build.py…")
result = subprocess.run(
    ['python3', str(ROOT / 'build.py')],
    capture_output=True, text=True, cwd=str(ROOT)
)
print(result.stdout)
if result.returncode != 0:
    print("STDERR:", result.stderr)
    raise RuntimeError(f"build.py failed with code {result.returncode}")


# ── REPORT ────────────────────────────────────────────────────────────────────
out_html = ROOT / 'site' / 'index.html'
html_size = out_html.stat().st_size if out_html.exists() else 0

with open(ROOT / 'data' / 'two-layers.json', encoding='utf-8') as f:
    final = json.load(f)

print("\n── PATCH COMPLETE ──────────────────────────────────")
print(f"site/index.html size: {html_size:,} bytes ({html_size/1024:.1f} KB)")
for ch in final['chapters']:
    en_2026 = ch['simulation']['paragraphs'].get('en', [])
    en_3026 = ch['archive']['paragraphs'].get('en', [])
    print(f"  Ch{ch['id']:2d} | 2026: {len(en_2026):2d} paras | 3026: {len(en_3026):2d} paras")
print("────────────────────────────────────────────────────")
